/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Auto generated by vite-plugin-dir2json
declare module "*views?dir2json&ext=.vue&lazy" {
  const json: {
  "AboutView": () => Promise<any>;
  "HomeView": () => Promise<any>;
};
  export default json;
}

declare module "*home?dir2json&1" {
  const json: {
  "h5": {
    "part1": {
      "part1": string;
    }
  },
  "pc": {
    "part1": {
      "part1": string;
    }
  }
};
  export default json;
}

declare module "*home?dir2json" {
  const json: {
  "h5": {
    "home1": {
      "home1": string;
    }
  },
  "pc": {
    "home1": {
      "home1": string;
    }
  }
};
  export default json;
}

declare module "*dir2json" {
  const json: any;
  export default json;
}