/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Auto generated by vite-plugin-dir2json
declare module "*home?dir2json" {
  const json: {
  "h5": {
    "home1": {
      "home1": string;
    }
  },
  "pc": {
    "home1": {
      "home1": string;
    }
  }
};
  export default json;
}

declare module "*dir2json" {
  const json: any;
  export default json;
}